#!/usr/bin/bash

VIRTUALENV_PATH=".venv"
VIRTUALENV_BIN_PATH="$VIRTUALENV_PATH/bin"
BUILDOUT_BIN_PATH="bin"
TEST_SCRIPT_PATH="automatic_test.cfg"

python3 -m venv $VIRTUALENV_PATH
$VIRTUALENV_BIN_PATH/pip3 install zc.buildout
$VIRTUALENV_BIN_PATH/buildout -c $TEST_SCRIPT_PATH bootstrap 
$BUILDOUT_BIN_PATH/buildout -c $TEST_SCRIPT_PATH
$BUILDOUT_BIN_PATH/run-tests
