version: 2.1

jobs:
  build_test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get upgrade
  pypi_publish:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to PyPI
            pip3 install virtualenv
            virtualenv venv
            source venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -U twine wheel setuptools
            python3 setup.py sdist bdist_wheel
            twine check dist/*
            twine upload dist/*
            deactivate
workflows:
  build_test_publish:
    jobs:
      - build_test:
          filters:
            tags:
              only: /.*/
      - pypi_publish:
          requires:
            - build_test
          filters:
            tags:
              only: /^v.*/
            branches: 
              ignore: /.*/


